brew 'bat'

cask 'raycast'
cask 'brave-browser'
cask 'obsidian'
cask 'visual-studio-code'
cask 'cleanshot'
cask 'wireshark'
cask 'powershell'
cask 'postman'
cask 'docker'
cask '1password'
cask 'jordanbaird-ice'