name: main

# Run on every push or pull request on the master branch.
on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    # Job for testing on linux
    linux:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - run: sh install.sh

    # Job for testing on macOS
    darwin:
        runs-on: macOS-latest
        steps:
        - uses: actions/checkout@v2
        - run: sh install.sh
